# Generated by Django 4.1.1 on 2022-09-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortedlink',
            name='visitors',
        ),
        migrations.AddField(
            model_name='shortedlink',
            name='visitors',
            field=models.ManyToManyField(null=True, to='main.visitor'),
        ),
    ]
