# Generated by Django 4.1.1 on 2022-09-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_shortedlink_visitors_shortedlink_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortedlink',
            name='visitors',
            field=models.ManyToManyField(to='main.visitor'),
        ),
    ]
